// Code generated by "stringer -type=FilterOperandType"; DO NOT EDIT.

package postgrest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilterOperandQuoted-1]
	_ = x[FilterOperandNumber-2]
}

const _FilterOperandType_name = "FilterOperandQuotedFilterOperandNumber"

var _FilterOperandType_index = [...]uint8{0, 19, 38}

func (i FilterOperandType) String() string {
	i -= 1
	if i < 0 || i >= FilterOperandType(len(_FilterOperandType_index)-1) {
		return "FilterOperandType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FilterOperandType_name[_FilterOperandType_index[i]:_FilterOperandType_index[i+1]]
}
