// Code generated by "stringer -type=Kind -linecomment"; DO NOT EDIT.

package importer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nullable-0]
	_ = x[Bool-1]
	_ = x[Boolean-2]
	_ = x[String-3]
	_ = x[Int8-4]
	_ = x[Int16-5]
	_ = x[Int32-6]
	_ = x[Int64-7]
	_ = x[Int128-8]
	_ = x[Int256-9]
	_ = x[UInt8-10]
	_ = x[UInt16-11]
	_ = x[UInt32-12]
	_ = x[UInt64-13]
	_ = x[UInt128-14]
	_ = x[UInt256-15]
	_ = x[Float-16]
	_ = x[Double-17]
	_ = x[Float32-18]
	_ = x[Float64-19]
	_ = x[Date-20]
	_ = x[Date32-21]
	_ = x[DateTime-22]
	_ = x[DateTime64-23]
	_ = x[LONGTEXT-24]
	_ = x[MEDIUMTEXT-25]
	_ = x[TINYTEXT-26]
	_ = x[TEXT-27]
	_ = x[LONGBLOB-28]
	_ = x[MEDIUMBLOB-29]
	_ = x[TINYBLOB-30]
	_ = x[BLOB-31]
	_ = x[VARCHAR-32]
	_ = x[CHAR-33]
	_ = x[TINYINT-34]
	_ = x[INT1-35]
	_ = x[SMALLINT-36]
	_ = x[INT2-37]
	_ = x[INT-38]
	_ = x[INT4-39]
	_ = x[INTEGER-40]
	_ = x[BIGINT-41]
}

const _Kind_name = "Nullable(Nothing)BoolBooleanStringInt8Int16Int32Int64Int128Int256UInt8UInt16UInt32UInt64UInt128UInt256FloatDoubleFloat32Float64DateDate32DateTime()DateTime64(9)LONGTEXTMEDIUMTEXTTINYTEXTTEXTLONGBLOBMEDIUMBLOBTINYBLOBBLOBVARCHARCHARTINYINTINT1SMALLINTINT2INTINT4INTEGERBIGINT"

var _Kind_index = [...]uint16{0, 17, 21, 28, 34, 38, 43, 48, 53, 59, 65, 70, 76, 82, 88, 95, 102, 107, 113, 120, 127, 131, 137, 147, 160, 168, 178, 186, 190, 198, 208, 216, 220, 227, 231, 238, 242, 250, 254, 257, 261, 268, 274}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
